name: powersync_attachments_stream
description: "A helper library for handling attachments when using PowerSync."
version: 0.0.1
repository: https://github.com/powersync-ja/powersync.dart
homepage: https://www.powersync.com/

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  async: ^2.11.0

  powersync_core: ^1.4.1
  logging: ^1.2.0
  sqlite_async: ^0.11.0
  path_provider: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15
