name: powersync_dart

packages:
  - packages/*
  - demos/*
  - demos/*/*

ide:
  intellij: false

scripts:
  prepare:
    description: Download SQLite3 WASM for demos
    run: |
      melos bootstrap && dart ./scripts/init_sqlite_wasm.dart && dart ./scripts/compile_webworker.dart && dart ./scripts/init_powersync_core_binary.dart
      for dir2 in demos/*; do
        if [ -d "$dir2" ]; then
            cd "$dir2"
            if [ -d "./web" ]; then
              dart run powersync:setup_web no_worker
            fi
            cd -
        fi
      done

  analyze:demos:
    description: Analyze Dart code in demos.
    run: dart analyze demos --fatal-infos

  analyze:packages:
    description: Analyze Dart code in packages.
    run: dart analyze packages --fatal-infos

  analyze:packages:pana:
    description: Analyze Dart packages with Pana
    exec: flutter pub global run pana --no-warning --exit-code-threshold 10
    packageFilters:
      noPrivate: true

  compile:webworker:
    description: Compile Javascript web worker distributable
    exec: dart run powersync_web_worker:compile_webworker
    packageFilters:
      scope:
        - powersync_web_worker

  format:
    description: Format Dart code.
    run: dart format .

  format:check:demos:
    description: Check formatting of Dart code in demos.
    run: dart format --output none --set-exit-if-changed demos

  format:check:packages:
    description: Check formatting of Dart code in packages.
    run: dart format --output none --set-exit-if-changed packages

  test:
    description: Run tests in a specific package.
    run: flutter test
    exec:
      concurrency: 1
    packageFilters:
      dirExists:
        - test
    # This tells Melos tests to ignore env variables passed to tests from `melos run test`
    # as they could change the behaviour of how tests filter packages.
    env:
      MELOS_TEST: true

  test:web:
    description: Run web tests in a specific package.
    run: dart test -p chrome
    exec:
      concurrency: 1
    packageFilters:
      dirExists:
        - test
    env:
      MELOS_TEST: true

  update:wasm: dart run scripts/init_sqlite_wasm.dart
