name: firebase_nodejs_todolist
description: Firebase NodeJS Todo List Demo
publish_to: "none"

version: 1.0.0+1
resolution: workspace
environment:
  sdk: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter

  powersync: ^2.0.0-wip.0
  sqlite3: ^3.2.0
  path_provider: ^2.1.1
  supabase_flutter: ^2.0.1
  path: ^1.8.3
  logging: ^1.1.1
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
