name: powersync_flutter_libs
description: This package no longer does anything.
version: 0.5.0+eol
repository: https://github.com/powersync-ja/powersync.dart
homepage: https://www.powersync.com/
resolution: workspace

environment:
  sdk: ^3.6.0
