name: powersync_benchmarks
description: PowerSync Benchmarks
publish_to: "none"

version: 0.1.0

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  powersync: ^1.15.1
  path_provider: ^2.1.1
  path: ^1.8.3
  logging: ^1.2.0
  universal_io: ^2.2.2
  sqlite_async: ^0.12.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
