name: Publish packages
on:
  push:
    tags:
      - "powersync-v[0-9]+.[0-9]+.[0-9]+*"
      - "powersync_attachments_helper-v[0-9]+.[0-9]+.[0-9]+*"
      - "powersync_flutter_libs-v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/prepare_wasm.yml

  github_release:
    runs-on: ubuntu-latest
    if: "${{ startsWith(github.ref_name, 'powersync-') }}"
    needs: [setup]
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
      - name: Create Draft Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          tag="${{ github.ref_name }}"
          version="${tag#powersync-v}"
          changes=$(awk "/## $version/{flag=1;next}/##/{flag=0}flag" packages/powersync/CHANGELOG.md)
          body="Release $tag
          $changes"
          gh release create "$tag" --title "$tag" --notes "$body"
          gh release upload "${{ github.ref_name }}" packages/powersync/assets/*.wasm
          gh release upload "${{ github.ref_name }}" packages/powersync/assets/powersync_db.worker.js

  publish_powersync:
    needs: [setup]
    permissions:
      id-token: write
    if: "${{ startsWith(github.ref_name, 'powersync-') }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      # Install Dart to install an OIDC token for publishing
      - uses: dart-lang/setup-dart@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"
      - run: dart pub get
      - run: tool/build-sh
        name: Build and copy devtools extension
        working-directory: packages/powersync_devtools_extension
      
      - name: Publish to pub.dev
        run: dart pub lish -f
        working-directory: packages/powersync

  publish_powersync_flutter_libs:
    permissions:
      id-token: write
    if: "${{ startsWith(github.ref_name, 'powersync_flutter_libs-') }}"
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: packages/powersync_flutter_libs

  publish_powersync_attachments_helper:
    permissions:
      id-token: write
    if: "${{ startsWith(github.ref_name, 'powersync_attachments_helper-') }}"
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: packages/powersync_attachments_helper
